use super::Error;

pub fn part1() -> Result<String, Error> {
    Ok("ayy lmao".into())
}

pub fn part2() -> Result<String, Error> {
    Ok("ayy lmao".into())
}
